-- Changelog: Create a Template, reworked
INSERT INTO "ChangeLogEntry" ("id","date","type","description","commitSha","createdAt")
VALUES (
  'cl_builder_rework_20260731',
  '2026-07-31',
  'Improvement',
  'The Create a Template screen has been reworked, mostly so that the modules part of it works the same way as Settings and then Modules and Fields does inside a tenant. Clicking one of the template buttons along the top now does something. It loads that template complete, every page, every module, every field, every setting, as your starting point. If it is a template you built, you are editing it and saving updates it. If it is one of the five that come with the product, you are starting a new one based on it, because those live in the code and cannot be changed from a screen. The form says which of the two you are doing at the top, before you can save anything, so there are no surprises. The top of the form is now three columns of similar width rather than two very wide boxes: name, description, and icon. The icon is a button showing your current choice. Click it and every icon appears at once so you can see them all together, with no captions cluttering it up. Pick one and it closes. Click again to change it or set it back to plain. It works from the keyboard and closes with Escape. The modules part now runs the full width of the page and behaves like the tenant screen it is meant to mirror. Click a module and everything about that module appears underneath it, including the fields it comes with. That last part was the real problem: modules used to look identical apart from their names, because the fields they actually ship with were not shown at all. Now they are, marked as coming with the module, and anything you add sits below them. The three dots menu on a module now offers rename, move up, move down, and delete. Delete means leave this module out of the template, so a tenant made from it simply will not have it. The module stays on screen with a line through it rather than vanishing, so you can see what you have left out and put it back from the same menu. Hide is gone, since there was nobody to hide a module from. Three things were removed for being more clutter than help: the automation library picker, and the two sections for setting up home dashboard panels and report pages. If you already saved a template using any of those, it keeps them and still creates them, exactly as before. Only the controls went. The AI receptionist setting has moved to the bottom, and a help link that led nowhere has been fixed. It turned out that the Learning Center can only be opened from inside a tenant, so those links were quietly going to the wrong place when clicked from this screen. A help tip with nowhere to send you now simply has no link.',
  'batch-builder-rework-20260731',
  NOW()
)
ON CONFLICT ("commitSha") DO NOTHING;
