-- Changelog: app shell — full-screen expands, presence survives it
INSERT INTO "ChangeLogEntry" ("id","date","type","description","commitSha","createdAt")
VALUES (
  'cl_app_shell_20260730',
  '2026-07-30',
  'Improvement',
  'Two fixes to the frame around every tenant portal screen. First, the hamburger button that hides the menus. It was supposed to give the page more room, but instead of the page growing into the space it jumped left and up, which read as the whole screen shifting rather than expanding. That was caused by three fixed measurements that tried to compensate for the menu column disappearing and got it wrong. They are gone. The page now holds its position exactly - the title, the text and the button itself all stay where they were - and the freed width is added to the right-hand side, so it genuinely looks like the content grew. Second, the coloured circles showing who else is online. Going full-screen used to make them disappear completely, because they sat inside the row of page tabs and full-screen hid that entire row - which also took away the notifications bell and the settings cog with them. Full-screen now hides only the tabs themselves, so the circles, the bell and the cog stay put in the top right whether you are full-screen or not. On Settings, Your account, the coloured marker beside your dot colour was never actually styled as a circle, so it showed as a highlighted letter instead. It is now the same circle you see everywhere else, drawn by the same code, so the two can never look different again. One thing we looked at and deliberately did not change: staff accounts - super admins, owners and auditors - do not appear in the online list at all, to anyone. That is not new, and it is stronger than merely hiding them on screen: they are never sent to your browser in the first place. We considered showing staff to each other while keeping them invisible to everyone in a tenant, and decided against it for now because the system does not record which tenant a staff member is looking at, so making it work would need a change to how data is stored for very little benefit while there is only one person on the admin side. The reasoning is written down in the code for whoever picks it up later. Also fixed along the way: the hamburger button was sitting on top of the first few pixels of the page title in the normal view, not just the full-screen one.',
  'batch-app-shell-20260730',
  NOW()
)
ON CONFLICT ("commitSha") DO NOTHING;
