-- Changelog: the Food Service template
INSERT INTO "ChangeLogEntry" ("id","date","type","description","commitSha","createdAt")
VALUES (
  'cl_food_service_template_20260731',
  '2026-07-31',
  'Feature',
  'There is a fifth template on the Create tenant screen, sitting to the right of Recruitment Marketing with a burger icon: Food Service. It is for restaurants, caterers and food trucks, and it is a full template rather than a quick one, meaning it arrives with everything the Field Services and Recruitment Marketing templates arrive with. A tenant made from it starts with the modules a food business actually uses, renamed to match the trade. Bookings read as Reservations, Products read as the Menu, Estimates read as Catering quotes, and Tasks read as Prep tasks. The things a kitchen has no use for are switched off from the start: work orders, equipment, vehicles, properties, job openings and service plans. The fields that matter are already there. Reservations carry a party size, a seating preference and an occasion. Customers carry allergies and dietary notes, and because those live on the customer rather than on one booking, a regular who told you about a nut allergy in March is still flagged in November. Catering quotes carry a headcount, a service style and an event date. The receptionist is set up for a restaurant phone rather than a contractor one. It books tables, takes catering enquiries, and answers questions about opening hours and where you are, and it does not try to log a fault report, because that is not what people ring a restaurant about. The home screen opens on tonight: today reservations in time order, the week count beside them, catering quotes by stage, and how many calls were answered. There are two report pages ready to go, one for covers and reservations and one for catering. The automation library is ordered the way a food business works, with the suggestions for capturing an enquiry and confirming a booking first. And the Learning Center is written for this trade, with its own guides on the book, the menu, catering quotes, prep, what to tell the receptionist, and how a normal service runs from open to close. Nothing about the four existing templates changed. Any tenant already created from one of them is untouched.',
  'batch-food-service-template-20260731',
  NOW()
)
ON CONFLICT ("commitSha") DO NOTHING;
