-- Changelog: two-factor authentication + account surface fixes
INSERT INTO "ChangeLogEntry" ("id","date","type","description","commitSha","createdAt")
VALUES (
  'cl_mfa_20260730',
  '2026-07-30',
  'Feature',
  'You can now turn on two-factor authentication for your account, under Settings, Your account. It is entirely optional and nothing changes for anyone who does not switch it on. When it is on, signing in asks for a six-digit code from an authenticator app on your phone after your password, so somebody who steals your password still cannot get in. Setting it up takes about a minute: you scan a square code with the app, type back the number it shows, and it is on. WHEN YOU TURN IT ON YOU ARE GIVEN TEN RECOVERY CODES, and you are shown them exactly once. Save them somewhere that is not your phone, because their entire purpose is to get you back in when your phone is what you have lost. A printed copy in a drawer, or your password manager on a different device, is what they are for. Each one works a single time and then it is gone, and the screen tells you how many you have left. If you lose the phone and the recovery codes as well, you are not locked out permanently: there is a command that can be run on the server to switch two-factor off for one account. It does nothing else at all, and whoever runs it still needs your password to sign in, so it is not a back door. You can also tick a box to have a device remembered for thirty days so you are not asked every single time. Changing your password, turning two-factor off, or having it cleared on the server all forget every remembered device immediately, so it can never become a second password you cannot take back. One other change on that screen, and it is worth explaining. CHANGING YOUR PASSWORD NOW ASKS FOR YOUR CURRENT PASSWORD FIRST. It did not before, and it should have. Anyone who reached a screen where you were already signed in, such as an unlocked laptop, could change your password without knowing the old one and lock you out of your own account. That change was also not being recorded anywhere and had no limit on repeated attempts. All three are fixed. Finally, the boxes on that screen were stretching the full width of the panel regardless of how much you actually type into them; they are now sized to their contents.',
  'batch-mfa-20260730',
  NOW()
)
ON CONFLICT ("commitSha") DO NOTHING;
