-- Changelog: AI Receptionist Only template + module visibility fixes
INSERT INTO "ChangeLogEntry" ("id","date","type","description","commitSha","createdAt")
VALUES (
  'cl_ai_receptionist_template_20260730',
  '2026-07-30',
  'Feature',
  'A fourth choice when you create a tenant: AI Receptionist Only, for a business that wants nothing more than its phone answered. It sits second in the row, between General and Field Services, and carries a phone icon. Picking it sets the new tenant up with a dashboard, the call log and contacts, and switches off everything else: no jobs, bookings, invoices, estimates, equipment, products, vehicles, properties, tasks, service plans or work orders. Analytics, Automations and Communication are switched off with them, since there is nothing to feed them. Billing stays on so the tenant can see its own plan, and the feedback channel stays on so the smallest customers still have a way to report a problem. It also adds four fields to a contact that a receptionist-only business actually needs: best time to call, preferred contact method, reason for calling, and callback promised by. As always you can tick or untick anything before you finish, and what you tick is what you get. While building it we checked the thing that matters more than the template itself: when a module is switched off, does it really disappear everywhere? Mostly yes, but we found three places where it did not, and all three are now fixed. The permissions screen was still offering switched-off modules as something you could grant people access to. The screen where you rename things was still offering wording for modules that were not there. And the notification settings still listed alerts for modules the tenant did not have, such as booking alerts for a tenant with no bookings. THESE THREE FIXES APPLY TO EVERY EXISTING TENANT, not just new ones - if you have a tenant with modules switched off, those three screens are now correct for it too. Nothing was deleted and nobody gained or lost access; these screens were simply offering things that were not there. Finally, on the create screen itself, the explanatory text beside the receptionist control and beside the demo control now lines up with the control it belongs to. It was being positioned by fixed measurements that only happened to look right at one text size, and drifted as soon as anything changed.',
  'batch-ai-receptionist-template-20260730',
  NOW()
)
ON CONFLICT ("commitSha") DO NOTHING;
