-- Changelog: tenant identity + billing surface
INSERT INTO "ChangeLogEntry" ("id","date","type","description","commitSha","createdAt")
VALUES (
  'cl_tenant_identity_20260730',
  '2026-07-30',
  'Improvement',
  'A tenant now looks and behaves the same everywhere you meet it on the master hub. In the tenants list, switching to the Panels view used to make a demo tenant look exactly like a real one - the amber Demo marker the table shows never appeared on a card. It does now, sitting beside the status marker at the top of the card. The "Manage panels" menu has always offered a Demo checkbox; until now that checkbox did nothing at all, because the cards were never built to show the field. It works, and a new build check makes sure every field the menu offers is a field the card actually draws, so this cannot quietly happen again to a future field. A tenant''s own page has caught up too. Its header used to show the status word and a single bare Suspend button; it now carries the status marker, the Demo marker where it applies, and the same three buttons the two list views use - open, suspend or resume, and delete - doing exactly what their counterparts do. TWO THINGS BEHAVE DIFFERENTLY, both deliberate. Suspending a tenant from its own page now asks you to confirm first, the same way both list views already did; previously that button suspended immediately with no prompt. And that page can now open the tenant portal directly, which it could not before - the line of text under the heading has been reworded to say so. Deleting still asks you to type the tenant''s name, exactly as before. Elsewhere on the hub, tables that had nothing to show were drawing a bordered box inside a bordered box - most visibly the Charges list on a tenant''s Billing and Usage page, which appeared as a box inside a box inside a box. All nine of those now use the same clean empty panel the tenants list already used, each with a short line explaining what will appear there, and the Charges one still points you at the button for adding the first charge. Finally, the Stripe button on that page has been renamed to say what it really does: it does not connect to an existing customer, it creates a new customer record inside Stripe for this tenant, and pressing it a second time changes nothing. The line beneath it now explains what the reference number underneath is instead of just printing it. Nothing about how that button works has changed - only its wording.',
  'batch-tenant-identity-20260730',
  NOW()
)
ON CONFLICT ("commitSha") DO NOTHING;
